In [1]:
100.0

100.0

In [2]:
0.00001

1e-05

In [3]:
10000000000000000.0

1e+16

In [4]:
100000000000000000.0

1e+17

In [5]:
0.1

0.1

In [6]:
0.01

0.01

In [7]:
0.001

0.001

In [8]:
0.00001

1e-05

In [9]:
0.0001

0.0001

In [10]:
0.00001

1e-05

In [11]:
0.0000001

1e-07

In [12]:
0.0000000001

1e-10

In [13]:
1e+02

100.0

In [14]:
1e+04

10000.0

In [15]:
1.23e+03

1230.0

# Excel

In [16]:
import pandas as pd
from pandas import Series, DataFrame, Index

import matplotlib.pyplot as plt
%matplotlib inline

In [19]:
Series(["a", "b"])

0    a
1    b
dtype: object

In [21]:
movies = pd.read_excel("movies.xls")

In [22]:
type(movies)

pandas.core.frame.DataFrame

In [23]:
movies

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
0,Intolerance: Love's Struggle Throughout the Ages,1916,Drama|History|War,NaN,USA,Not Rated,123,1.33,385907.0,NaN,...,436,22,9.0,481,691,1,10718,88,69.0,8.0
1,Over the Hill to the Poorhouse,1920,Crime|Drama,NaN,USA,NaN,110,1.33,100000.0,3000000.0,...,2,2,0.0,4,0,1,5,1,1.0,4.8
2,The Big Parade,1925,Drama|Romance|War,NaN,USA,Not Rated,151,1.33,245000.0,NaN,...,81,12,6.0,108,226,0,4849,45,48.0,8.3
3,Metropolis,1927,Drama|Sci-Fi,German,Germany,Not Rated,145,1.33,6000000.0,26435.0,...,136,23,18.0,203,12000,1,111841,413,260.0,8.3
4,Pandora's Box,1929,Crime|Drama|Romance,German,Germany,Not Rated,110,1.33,NaN,9950.0,...,426,20,3.0,455,926,1,7431,84,71.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,Twin Falls Idaho,1999,Drama,English,USA,R,111,1.85,500000.0,985341.0,...,980,505,482.0,3166,180,0,3479,87,54.0,7.3
1334,Universal Soldier: The Return,1999,Action|Sci-Fi,English,USA,R,83,1.85,24000000.0,10431220.0,...,2000,577,485.0,4024,401,0,24216,162,75.0,4.1
1335,Varsity Blues,1999,Comedy|Drama|Romance|Sport,English,USA,R,106,1.85,16000000.0,52885587.0,...,23000,255,35.0,23369,0,0,35312,267,67.0,6.4
1336,Wild Wild West,1999,Action|Comedy|Sci-Fi|Western,English,USA,PG-13,106,1.85,170000000.0,113745408.0,...,10000,4000,582.0,15870,0,2,129601,648,85.0,4.8
1337,Wing Commander,1999,Action|Adventure|Sci-Fi,English,USA,PG-13,100,2.35,30000000.0,11576087.0,...,811,586,362.0,2497,858,3,14747,338,85.0,4.1

In [27]:
movies = pd.read_excel("movies.xls", sheet_name=3)
movies

ValueError: Worksheet index 3 is invalid, 3 worksheets found

In [28]:
xlsx = pd.ExcelFile("movies.xls")
type(xlsx)

pandas.io.excel._base.ExcelFile

In [29]:
xlsx.sheet_names

['1900s', '2000s', '2010s']

In [30]:
len(xlsx.sheet_names)

3

In [32]:
movies_sheets = []
for sheet in xlsx.sheet_names:
    movies_sheets.append(xlsx.parse(sheet))
movies_sheets

[                                                  Title  Year  \
 0     Intolerance: Love's Struggle Throughout the Ages   1916
 1                       Over the Hill to the Poorhouse   1920
 2                                       The Big Parade   1925
 3                                           Metropolis   1927
 4                                        Pandora's Box   1929
 ...                                                 ...   ...
 1333                                  Twin Falls Idaho   1999
 1334                     Universal Soldier: The Return   1999
 1335                                     Varsity Blues   1999
 1336                                    Wild Wild West   1999
 1337                                    Wing Commander   1999

                             Genres Language  Country Content Rating  Duration  \
 0                Drama|History|War      NaN      USA      Not Rated       123
 1                      Crime|Drama      NaN      USA            NaN       110
 2                Drama|Romance|War      NaN      USA      Not Rated       151
 3                     Drama|Sci-Fi   German  Germany      Not Rated       145
 4              Crime|Drama|Romance   German  Germany      Not Rated       110
 ...                            ...      ...      ...            ...       ...
 1333                         Drama  English      USA              R       111
 1334                 Action|Sci-Fi  English      USA              R        83
 1335    Comedy|Drama|Romance|Sport  English      USA              R       106
 1336  Action|Comedy|Sci-Fi|Western  English      USA          PG-13       106
 1337       Action|Adventure|Sci-Fi  English      USA          PG-13       100

       Aspect Ratio       Budget  Gross Earnings  ... Facebook Likes - Actor 1  \
 0             1.33     385907.0             NaN  ...                      436
 1             1.33     100000.0       3000000.0  ...                        2
 2             1.33     245000.0             NaN  ...                       81
 3             1.33    6000000.0         26435.0  ...                      136
 4             1.33          NaN          9950.0  ...                      426
 ...            ...          ...             ...  ...                      ...
 1333          1.85     500000.0        985341.0  ...                      980
 1334          1.85   24000000.0      10431220.0  ...                     2000
 1335          1.85   16000000.0      52885587.0  ...                    23000
 1336          1.85  170000000.0     113745408.0  ...                    10000
 1337          2.35   30000000.0      11576087.0  ...                      811

      Facebook Likes - Actor 2 Facebook Likes - Actor 3  \
 0                          22                      9.0
 1                           2                      0.0
 2                          12                      6.0
 3                          23                     18.0
 4                          20                      3.0
 ...                       ...                      ...
 1333                      505                    482.0
 1334                      577                    485.0
 1335                      255                     35.0
 1336                     4000                    582.0
 1337                      586                    362.0

      Facebook Likes - cast Total  Facebook likes - Movie  \
 0                            481                     691
 1                              4                       0
 2                            108                     226
 3                            203                   12000
 4                            455                     926
 ...                          ...                     ...
 1333                        3166                     180
 1334                        4024                     401
 1335                       23369                       0
 1336                       15870                       0
 1337                        2497                     858

       Facenumber in posters  User Votes  Reviews by Users  Reviews by Crtiics  \
 0                         1       10718                88                69.0
 1                         1           5                 1                 1.0
 2                         0        4849                45                48.0
 3                         1      111841               413               260.0
 4                         1        7431                84                71.0
 ...                     ...         ...               ...                 ...
 1333                      0        3479                87                54.0
 1334                      0       24216               162                75.0
 1335                      0       35312               267                67.0
 1336                      2      129601               648                85.0
 1337                      3       14747               338                85.0

       IMDB Score
 0            8.0
 1            4.8
 2            8.3
 3            8.3
 4            8.0
 ...          ...
 1333         7.3
 1334         4.1
 1335         6.4
 1336         4.8
 1337         4.1

 [1338 rows x 25 columns],
                                   Title  Year  \
 0                       102 Dalmatians   2000
 1                              28 Days   2000
 2                            3 Strikes   2000
 3                             Aberdeen   2000
 4                All the Pretty Horses   2000
 ...                                 ...   ...
 2095          X-Men Origins: Wolverine   2009
 2096                          Year One   2009
 2097                   Youth in Revolt   2009
 2098  ZMD: Zombies of Mass Destruction   2009
 2099                        Zombieland   2009

                                         Genres Language Country  \
 0                      Adventure|Comedy|Family  English     USA
 1                                 Comedy|Drama  English     USA
 2                                       Comedy  English     USA
 3                                        Drama  English      UK
 4                        Drama|Romance|Western  English     USA
 ...                                        ...      ...     ...
 2095  Action|Adventure|Fantasy|Sci-Fi|Thriller  English     USA
 2096                          Adventure|Comedy  English     USA
 2097                      Comedy|Drama|Romance  English     USA
 2098                      Comedy|Horror|Sci-Fi  English     USA
 2099            Adventure|Comedy|Horror|Sci-Fi  English     USA

      Content Rating  Duration  Aspect Ratio       Budget  Gross Earnings  ...  \
 0                 G     100.0          1.85   85000000.0      66941559.0  ...
 1             PG-13     103.0          1.37   43000000.0      37035515.0  ...
 2                 R      82.0          1.85    6000000.0       9821335.0  ...
 3               NaN     106.0          1.85    6500000.0         64148.0  ...
 4             PG-13     220.0          2.35   57000000.0      15527125.0  ...
 ...             ...       ...           ...          ...             ...  ...
 2095          PG-13     119.0          2.35  150000000.0     179883016.0  ...
 2096          PG-13     100.0          1.85   60000000.0      43337279.0  ...
 2097              R      90.0          1.85   18000000.0      15281286.0  ...
 2098              R      89.0          1.85     500000.0             NaN  ...
 2099              R      88.0          2.35   23600000.0      75590286.0  ...

      Facebook Likes - Actor 1 Facebook Likes - Actor 2  \
 0                      2000.0                    795.0
 1                     12000.0                  10000.0
 2                       939.0                    706.0
 3                       844.0                      2.0
 4                     13000.0                    861.0
 ...                       ...                      ...
 2095                  20000.0                  16000.0
 2096                  10000.0                   1000.0
 2097                  12000.0                    904.0
 2098                    199.0                     37.0
 2099                  15000.0                  13000.0

      Facebook Likes - Actor 3 Facebook Likes - cast Total  \
 0                       439.0                        4182
 1                       664.0                       23864
 2                       585.0                        3354
 3                         0.0                         846
 4                       820.0                       15006
 ...                       ...                         ...
 2095                   2000.0                       40054
 2096                    485.0                       12258
 2097                    729.0                       16004
 2098                     23.0                         292
 2099                     11.0                       28011

       Facebook likes - Movie  Facenumber in posters  User Votes  \
 0                        372                      1       26413
 1                          0                      1       34597
 2                        118                      1        1415
 3                        260                      0        2601
 4                        652                      2       11388
 ...                      ...                    ...         ...
 2095                       0                      0      361924
 2096                       0                      2       76770
 2097                       0                      2       64646
 2098                       0                      0        3650
 2099                   26000                      4      386217

       Reviews by Users  Reviews by Crtiics  IMDB Score
 0                 77.0                84.0         4.8
 1                194.0               116.0         6.0
 2                 10.0                22.0         4.0
 3                 35.0                28.0         7.3
 4                183.0                85.0         5.8
 ...                ...                 ...         ...
 2095             641.0               350.0         6.7
 2096             203.0               170.0         4.9
 2097             105.0               192.0         6.5
 2098              39.0                64.0         5.1
 2099             553.0               445.0         7.7

 [2100 rows x 25 columns],
                                      Title    Year  \
 0                               127 Hours   2010.0
 1                             3 Backyards   2010.0
 2                                       3   2010.0
 3               8: The Mormon Proposition   2010.0
 4     A Turtle's Tale: Sammy's Adventures   2010.0
 ...                                    ...     ...
 1599              War & Peace                  NaN
 1600                    Wings                  NaN
 1601               Wolf Creek                  NaN
 1602        Wuthering Heights                  NaN
 1603  Yu-Gi-Oh! Duel Monsters                  NaN

                                          Genres  Language    Country  \
 0            Adventure|Biography|Drama|Thriller   English        USA
 1                                         Drama   English        USA
 2                          Comedy|Drama|Romance    German    Germany
 3                                   Documentary   English        USA
 4                    Adventure|Animation|Family   English     France
 ...                                         ...       ...        ...
 1599                  Drama|History|Romance|War   English         UK
 1600                               Comedy|Drama   English        USA
 1601                      Drama|Horror|Thriller   English  Australia
 1602                              Drama|Romance   English         UK
 1603  Action|Adventure|Animation|Family|Fantasy  Japanese      Japan

      Content Rating  Duration  Aspect Ratio      Budget  Gross Earnings  ...  \
 0                 R      94.0          1.85  18000000.0      18329466.0  ...
 1                 R      88.0           NaN    300000.0             NaN  ...
 2           Unrated     119.0          2.35         NaN         59774.0  ...
 3                 R      80.0          1.78   2500000.0         99851.0  ...
 4                PG      88.0          2.35         NaN             NaN  ...
 ...             ...       ...           ...         ...             ...  ...
 1599          TV-14       NaN         16.00         NaN             NaN  ...
 1600            NaN      30.0          1.33         NaN             NaN  ...
 1601            NaN       NaN          2.00         NaN             NaN  ...
 1602            NaN     142.0           NaN         NaN             NaN  ...
 1603            NaN      24.0           NaN         NaN             NaN  ...

      Facebook Likes - Actor 1 Facebook Likes - Actor 2  \
 0                     11000.0                    642.0
 1                       795.0                    659.0
 2                        24.0                     20.0
 3                       191.0                     12.0
 4                       783.0                    749.0
 ...                       ...                      ...
 1599                   1000.0                    888.0
 1600                    685.0                    511.0
 1601                    511.0                    457.0
 1602                  27000.0                    698.0
 1603                      0.0                      NaN

      Facebook Likes - Actor 3 Facebook Likes - cast Total  \
 0                       223.0                       11984
 1                       301.0                        1884
 2                         9.0                          69
 3                         5.0                         210
 4                       602.0                        3874
 ...                       ...                         ...
 1599                    502.0                        4528
 1600                    424.0                        1884
 1601                    206.0                        1617
 1602                    427.0                       29196
 1603                      NaN                           0

       Facebook likes - Movie  Facenumber in posters  User Votes  \
 0                      63000                    0.0      279179
 1                         92                    0.0         554
 2                       2000                    0.0        4212
 3                          0                    0.0        1138
 4                          0                    2.0        5385
 ...                      ...                    ...         ...
 1599                   11000                    1.0        9277
 1600                    1000                    5.0        7646
 1601                     954                    0.0         726
 1602                       0                    2.0        6053
 1603                     124                    0.0       12417

       Reviews by Users  Reviews by Crtiics  IMDB Score
 0                440.0               450.0         7.6
 1                 23.0                20.0         5.2
 2                 18.0                76.0         6.8
 3                 30.0                28.0         7.1
 4                 22.0                56.0         6.1
 ...                ...                 ...         ...
 1599              44.0                10.0         8.2
 1600              56.0                19.0         7.3
 1601               6.0                 2.0         7.1
 1602              33.0                 9.0         7.7
 1603              51.0                 6.0         7.0

 [1604 rows x 25 columns]]

In [34]:
type(movies_sheets[0])

pandas.core.frame.DataFrame

In [35]:
movies = pd.concat(movies_sheets)
movies

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
0,Intolerance: Love's Struggle Throughout the Ages,1916.0,Drama|History|War,NaN,USA,Not Rated,123.0,1.33,385907.0,NaN,...,436.0,22.0,9.0,481,691,1.0,10718,88.0,69.0,8.0
1,Over the Hill to the Poorhouse,1920.0,Crime|Drama,NaN,USA,NaN,110.0,1.33,100000.0,3000000.0,...,2.0,2.0,0.0,4,0,1.0,5,1.0,1.0,4.8
2,The Big Parade,1925.0,Drama|Romance|War,NaN,USA,Not Rated,151.0,1.33,245000.0,NaN,...,81.0,12.0,6.0,108,226,0.0,4849,45.0,48.0,8.3
3,Metropolis,1927.0,Drama|Sci-Fi,German,Germany,Not Rated,145.0,1.33,6000000.0,26435.0,...,136.0,23.0,18.0,203,12000,1.0,111841,413.0,260.0,8.3
4,Pandora's Box,1929.0,Crime|Drama|Romance,German,Germany,Not Rated,110.0,1.33,NaN,9950.0,...,426.0,20.0,3.0,455,926,1.0,7431,84.0,71.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1599,War & Peace,NaN,Drama|History|Romance|War,English,UK,TV-14,NaN,16.00,NaN,NaN,...,1000.0,888.0,502.0,4528,11000,1.0,9277,44.0,10.0,8.2
1600,Wings,NaN,Comedy|Drama,English,USA,NaN,30.0,1.33,NaN,NaN,...,685.0,511.0,424.0,1884,1000,5.0,7646,56.0,19.0,7.3
1601,Wolf Creek,NaN,Drama|Horror|Thriller,English,Australia,NaN,NaN,2.00,NaN,NaN,...,511.0,457.0,206.0,1617,954,0.0,726,6.0,2.0,7.1
1602,Wuthering Heights,NaN,Drama|Romance,English,UK,NaN,142.0,NaN,NaN,NaN,...,27000.0,698.0,427.0,29196,0,2.0,6053,33.0,9.0,7.7
1603,Yu-Gi-Oh! Duel Monsters,NaN,Action|Adventure|Animation|Family|Fantasy,Japanese,Japan,NaN,24.0,NaN,NaN,NaN,...,0.0,NaN,NaN,0,124,0.0,12417,51.0,6.0,7.0

In [36]:
movies.shape

(5042, 25)

In [39]:
movies.tail(n=10)

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
1594,Trapped,NaN,Crime|Drama|Thriller,Icelandic,Iceland,NaN,511.0,16.00,NaN,NaN,...,147.0,63.0,51.0,307,0,0.0,2308,19.0,16.0,8.2
1595,Twisted,NaN,Drama|Mystery|Thriller,English,USA,NaN,60.0,16.00,NaN,NaN,...,629.0,512.0,398.0,2758,915,2.0,7945,22.0,4.0,7.5
1596,Unforgettable,NaN,Drama|Mystery,NaN,USA,NaN,60.0,NaN,NaN,NaN,...,654.0,426.0,405.0,1906,0,1.0,12854,44.0,14.0,6.7
1597,Unforgotten,NaN,Crime|Drama,English,UK,NaN,45.0,NaN,NaN,NaN,...,416.0,171.0,132.0,1816,0,2.0,1824,9.0,2.0,7.9
1598,Veronica Mars,NaN,Crime|Drama|Mystery,English,USA,TV-14,44.0,1.78,NaN,NaN,...,937.0,828.0,724.0,3318,0,1.0,55524,315.0,47.0,8.4
1599,War & Peace,NaN,Drama|History|Romance|War,English,UK,TV-14,NaN,16.00,NaN,NaN,...,1000.0,888.0,502.0,4528,11000,1.0,9277,44.0,10.0,8.2
1600,Wings,NaN,Comedy|Drama,English,USA,NaN,30.0,1.33,NaN,NaN,...,685.0,511.0,424.0,1884,1000,5.0,7646,56.0,19.0,7.3
1601,Wolf Creek,NaN,Drama|Horror|Thriller,English,Australia,NaN,NaN,2.00,NaN,NaN,...,511.0,457.0,206.0,1617,954,0.0,726,6.0,2.0,7.1
1602,Wuthering Heights,NaN,Drama|Romance,English,UK,NaN,142.0,NaN,NaN,NaN,...,27000.0,698.0,427.0,29196,0,2.0,6053,33.0,9.0,7.7
1603,Yu-Gi-Oh! Duel Monsters,NaN,Action|Adventure|Animation|Family|Fantasy,Japanese,Japan,NaN,24.0,NaN,NaN,NaN,...,0.0,NaN,NaN,0,124,0.0,12417,51.0,6.0,7.0

In [42]:
movies.index

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603],
           dtype='int64', length=5042)

In [43]:
movies.loc[0]

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
0,Intolerance: Love's Struggle Throughout the Ages,1916.0,Drama|History|War,NaN,USA,Not Rated,123.0,1.33,385907.0,NaN,...,436.0,22.0,9.0,481,691,1.0,10718,88.0,69.0,8.0
0,102 Dalmatians,2000.0,Adventure|Comedy|Family,English,USA,G,100.0,1.85,85000000.0,66941559.0,...,2000.0,795.0,439.0,4182,372,1.0,26413,77.0,84.0,4.8
0,127 Hours,2010.0,Adventure|Biography|Drama|Thriller,English,USA,R,94.0,1.85,18000000.0,18329466.0,...,11000.0,642.0,223.0,11984,63000,0.0,279179,440.0,450.0,7.6

In [44]:
movies.columns

Index(['Title', 'Year', 'Genres', 'Language', 'Country', 'Content Rating',
       'Duration', 'Aspect Ratio', 'Budget', 'Gross Earnings', 'Director',
       'Actor 1', 'Actor 2', 'Actor 3', 'Facebook Likes - Director',
       'Facebook Likes - Actor 1', 'Facebook Likes - Actor 2',
       'Facebook Likes - Actor 3', 'Facebook Likes - cast Total',
       'Facebook likes - Movie', 'Facenumber in posters', 'User Votes',
       'Reviews by Users', 'Reviews by Crtiics', 'IMDB Score'],
      dtype='object')

In [45]:
movies.columns.values

array(['Title', 'Year', 'Genres', 'Language', 'Country', 'Content Rating',
       'Duration', 'Aspect Ratio', 'Budget', 'Gross Earnings', 'Director',
       'Actor 1', 'Actor 2', 'Actor 3', 'Facebook Likes - Director',
       'Facebook Likes - Actor 1', 'Facebook Likes - Actor 2',
       'Facebook Likes - Actor 3', 'Facebook Likes - cast Total',
       'Facebook likes - Movie', 'Facenumber in posters', 'User Votes',
       'Reviews by Users', 'Reviews by Crtiics', 'IMDB Score'],
      dtype=object)

In [46]:
type(movies.columns.values)

numpy.ndarray

In [47]:
list(movies.columns)

['Title',
 'Year',
 'Genres',
 'Language',
 'Country',
 'Content Rating',
 'Duration',
 'Aspect Ratio',
 'Budget',
 'Gross Earnings',
 'Director',
 'Actor 1',
 'Actor 2',
 'Actor 3',
 'Facebook Likes - Director',
 'Facebook Likes - Actor 1',
 'Facebook Likes - Actor 2',
 'Facebook Likes - Actor 3',
 'Facebook Likes - cast Total',
 'Facebook likes - Movie',
 'Facenumber in posters',
 'User Votes',
 'Reviews by Users',
 'Reviews by Crtiics',
 'IMDB Score']

In [49]:
movies["IMDB Score"]

0       8.0
1       4.8
2       8.3
3       8.3
4       8.0
       ...
1599    8.2
1600    7.3
1601    7.1
1602    7.7
1603    7.0
Name: IMDB Score, Length: 5042, dtype: float64

In [50]:
movies.Title

0       Intolerance: Love's Struggle Throughout the Ages
1                         Over the Hill to the Poorhouse
2                                         The Big Parade
3                                             Metropolis
4                                          Pandora's Box
                              ...
1599                             War & Peace
1600                                   Wings
1601                              Wolf Creek
1602                       Wuthering Heights
1603                 Yu-Gi-Oh! Duel Monsters
Name: Title, Length: 5042, dtype: object

In [51]:
movies["Title"]

0       Intolerance: Love's Struggle Throughout the Ages
1                         Over the Hill to the Poorhouse
2                                         The Big Parade
3                                             Metropolis
4                                          Pandora's Box
                              ...
1599                             War & Peace
1600                                   Wings
1601                              Wolf Creek
1602                       Wuthering Heights
1603                 Yu-Gi-Oh! Duel Monsters
Name: Title, Length: 5042, dtype: object

In [52]:
movies["Title"][3:7]

3             Metropolis
4          Pandora's Box
5    The Broadway Melody
6          Hell's Angels
Name: Title, dtype: object

In [54]:
movies[["Title", "IMDB Score", "Year"]]

                                                  Title  IMDB Score    Year
0     Intolerance: Love's Struggle Throughout the Ages          8.0  1916.0
1                       Over the Hill to the Poorhouse          4.8  1920.0
2                                       The Big Parade          8.3  1925.0
3                                           Metropolis          8.3  1927.0
4                                        Pandora's Box          8.0  1929.0
...                                                 ...         ...     ...
1599                           War & Peace                      8.2     NaN
1600                                 Wings                      7.3     NaN
1601                            Wolf Creek                      7.1     NaN
1602                     Wuthering Heights                      7.7     NaN
1603               Yu-Gi-Oh! Duel Monsters                      7.0     NaN

[5042 rows x 3 columns]

In [55]:
movies.describe()

,Year,Duration,Aspect Ratio,Budget,Gross Earnings,Facebook Likes - Director,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
count,4935.000000,5028.000000,4714.000000,4.551000e+03,4.159000e+03,4938.000000,5035.000000,5029.000000,5020.000000,5042.000000,5042.000000,5029.000000,5.042000e+03,5022.000000,4993.000000,5042.000000
mean,2002.470517,107.201074,2.220403,3.975262e+07,4.846841e+07,686.621709,6561.323932,1652.080533,645.009761,9700.959143,7527.457160,1.371446,8.368475e+04,272.770808,140.194272,6.442007
std,12.474599,25.197441,1.385113,2.061149e+08,6.845299e+07,2813.602405,15021.977635,4042.774685,1665.041728,18165.101925,19322.070537,2.013683,1.384940e+05,377.982886,121.601675,1.125189
min,1916.000000,7.000000,1.180000,2.180000e+02,1.620000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000e+00,1.000000,1.000000,1.600000
25%,1999.000000,93.000000,1.850000,6.000000e+06,5.340988e+06,7.000000,614.500000,281.000000,133.000000,1411.250000,0.000000,0.000000,8.599250e+03,65.000000,50.000000,5.800000
50%,2005.000000,103.000000,2.350000,2.000000e+07,2.551750e+07,49.000000,988.000000,595.000000,371.500000,3091.000000,166.000000,1.000000,3.437100e+04,156.000000,110.000000,6.600000
75%,2011.000000,118.000000,2.350000,4.500000e+07,6.230944e+07,194.750000,11000.000000,918.000000,636.000000,13758.750000,3000.000000,2.000000,9.634700e+04,326.000000,195.000000,7.200000
max,2016.000000,511.000000,16.000000,1.221550e+10,7.605058e+08,23000.000000,640000.000000,137000.000000,23000.000000,656730.000000,349000.000000,43.000000,1.689764e+06,5060.000000,813.000000,9.500000

In [56]:
movies

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
0,Intolerance: Love's Struggle Throughout the Ages,1916.0,Drama|History|War,NaN,USA,Not Rated,123.0,1.33,385907.0,NaN,...,436.0,22.0,9.0,481,691,1.0,10718,88.0,69.0,8.0
1,Over the Hill to the Poorhouse,1920.0,Crime|Drama,NaN,USA,NaN,110.0,1.33,100000.0,3000000.0,...,2.0,2.0,0.0,4,0,1.0,5,1.0,1.0,4.8
2,The Big Parade,1925.0,Drama|Romance|War,NaN,USA,Not Rated,151.0,1.33,245000.0,NaN,...,81.0,12.0,6.0,108,226,0.0,4849,45.0,48.0,8.3
3,Metropolis,1927.0,Drama|Sci-Fi,German,Germany,Not Rated,145.0,1.33,6000000.0,26435.0,...,136.0,23.0,18.0,203,12000,1.0,111841,413.0,260.0,8.3
4,Pandora's Box,1929.0,Crime|Drama|Romance,German,Germany,Not Rated,110.0,1.33,NaN,9950.0,...,426.0,20.0,3.0,455,926,1.0,7431,84.0,71.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1599,War & Peace,NaN,Drama|History|Romance|War,English,UK,TV-14,NaN,16.00,NaN,NaN,...,1000.0,888.0,502.0,4528,11000,1.0,9277,44.0,10.0,8.2
1600,Wings,NaN,Comedy|Drama,English,USA,NaN,30.0,1.33,NaN,NaN,...,685.0,511.0,424.0,1884,1000,5.0,7646,56.0,19.0,7.3
1601,Wolf Creek,NaN,Drama|Horror|Thriller,English,Australia,NaN,NaN,2.00,NaN,NaN,...,511.0,457.0,206.0,1617,954,0.0,726,6.0,2.0,7.1
1602,Wuthering Heights,NaN,Drama|Romance,English,UK,NaN,142.0,NaN,NaN,NaN,...,27000.0,698.0,427.0,29196,0,2.0,6053,33.0,9.0,7.7
1603,Yu-Gi-Oh! Duel Monsters,NaN,Action|Adventure|Animation|Family|Fantasy,Japanese,Japan,NaN,24.0,NaN,NaN,NaN,...,0.0,NaN,NaN,0,124,0.0,12417,51.0,6.0,7.0

In [57]:
movies.iloc[2, 2]

'Drama|Romance|War'

In [58]:
movies.iloc[1, 6]

110.0

In [61]:
movies.iloc[1:4, 6:10]

   Duration  Aspect Ratio     Budget  Gross Earnings
1     110.0          1.33   100000.0       3000000.0
2     151.0          1.33   245000.0             NaN
3     145.0          1.33  6000000.0         26435.0

In [64]:
series01 = movies["Country"] == "Germany"
series01

0       False
1       False
2       False
3        True
4        True
        ...
1599    False
1600    False
1601    False
1602    False
1603    False
Name: Country, Length: 5042, dtype: bool

In [66]:
movies.loc[series01]

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
3,Metropolis,1927.0,Drama|Sci-Fi,German,Germany,Not Rated,145.0,1.33,6000000.0,26435.0,...,136.0,23.0,18.0,203,12000,1.0,111841,413.0,260.0,8.3
4,Pandora's Box,1929.0,Crime|Drama|Romance,German,Germany,Not Rated,110.0,1.33,NaN,9950.0,...,426.0,20.0,3.0,455,926,1.0,7431,84.0,71.0,8.0
1058,City of Angels,1998.0,Drama|Fantasy|Romance,English,Germany,PG-13,114.0,2.35,55000000.0,78745923.0,...,12000.0,702.0,539.0,13905,0,1.0,94407,322.0,110.0,6.7
1059,Clay Pigeons,1998.0,Comedy|Crime,English,Germany,R,104.0,1.85,8000000.0,1789892.0,...,1000.0,261.0,168.0,1795,515,1.0,9494,109.0,49.0,6.6
1110,Run Lola Run,1998.0,Crime|Drama,German,Germany,R,81.0,1.85,3500000.0,7267324.0,...,486.0,37.0,34.0,623,0,1.0,161471,709.0,181.0,7.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489,Cloud Atlas,2012.0,Drama|Sci-Fi,English,Germany,R,172.0,2.35,102000000.0,27098580.0,...,15000.0,5000.0,1000.0,22686,124000,5.0,284825,828.0,511.0,7.5
573,Resident Evil: Retribution,2012.0,Action|Horror|Sci-Fi|Thriller,English,Germany,R,96.0,2.35,65000000.0,42345531.0,...,14000.0,1000.0,974.0,17913,32000,0.0,104831,423.0,239.0,5.4
706,Banshee Chapter,2013.0,Horror|Thriller,English,Germany,R,87.0,NaN,950000.0,NaN,...,696.0,371.0,302.0,1618,2000,1.0,6265,56.0,78.0,5.5
759,Hansel & Gretel: Witch Hunters,2013.0,Action|Fantasy|Horror,English,Germany,R,98.0,2.35,50000000.0,55682070.0,...,10000.0,520.0,467.0,11946,45000,2.0,159868,304.0,349.0,6.1
1320,Stung,2015.0,Comedy|Horror,English,Germany,Not Rated,87.0,2.35,2500000.0,NaN,...,968.0,625.0,577.0,3157,0,0.0,3119,23.0,95.0,5.0

In [67]:
movies.loc[movies["Country"] == "Germany"]

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
3,Metropolis,1927.0,Drama|Sci-Fi,German,Germany,Not Rated,145.0,1.33,6000000.0,26435.0,...,136.0,23.0,18.0,203,12000,1.0,111841,413.0,260.0,8.3
4,Pandora's Box,1929.0,Crime|Drama|Romance,German,Germany,Not Rated,110.0,1.33,NaN,9950.0,...,426.0,20.0,3.0,455,926,1.0,7431,84.0,71.0,8.0
1058,City of Angels,1998.0,Drama|Fantasy|Romance,English,Germany,PG-13,114.0,2.35,55000000.0,78745923.0,...,12000.0,702.0,539.0,13905,0,1.0,94407,322.0,110.0,6.7
1059,Clay Pigeons,1998.0,Comedy|Crime,English,Germany,R,104.0,1.85,8000000.0,1789892.0,...,1000.0,261.0,168.0,1795,515,1.0,9494,109.0,49.0,6.6
1110,Run Lola Run,1998.0,Crime|Drama,German,Germany,R,81.0,1.85,3500000.0,7267324.0,...,486.0,37.0,34.0,623,0,1.0,161471,709.0,181.0,7.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489,Cloud Atlas,2012.0,Drama|Sci-Fi,English,Germany,R,172.0,2.35,102000000.0,27098580.0,...,15000.0,5000.0,1000.0,22686,124000,5.0,284825,828.0,511.0,7.5
573,Resident Evil: Retribution,2012.0,Action|Horror|Sci-Fi|Thriller,English,Germany,R,96.0,2.35,65000000.0,42345531.0,...,14000.0,1000.0,974.0,17913,32000,0.0,104831,423.0,239.0,5.4
706,Banshee Chapter,2013.0,Horror|Thriller,English,Germany,R,87.0,NaN,950000.0,NaN,...,696.0,371.0,302.0,1618,2000,1.0,6265,56.0,78.0,5.5
759,Hansel & Gretel: Witch Hunters,2013.0,Action|Fantasy|Horror,English,Germany,R,98.0,2.35,50000000.0,55682070.0,...,10000.0,520.0,467.0,11946,45000,2.0,159868,304.0,349.0,6.1
1320,Stung,2015.0,Comedy|Horror,English,Germany,Not Rated,87.0,2.35,2500000.0,NaN,...,968.0,625.0,577.0,3157,0,0.0,3119,23.0,95.0,5.0

In [68]:
movies.loc[(movies["Country"] == "Germany") | (movies["Country"] == "Japan")]

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
3,Metropolis,1927.0,Drama|Sci-Fi,German,Germany,Not Rated,145.0,1.33,6.000000e+06,26435.0,...,136.0,23.0,18.0,203,12000,1.0,111841,413.0,260.0,8.3
4,Pandora's Box,1929.0,Crime|Drama|Romance,German,Germany,Not Rated,110.0,1.33,NaN,9950.0,...,426.0,20.0,3.0,455,926,1.0,7431,84.0,71.0,8.0
61,Seven Samurai,1954.0,Action|Adventure|Drama,Japanese,Japan,Unrated,202.0,1.37,2.000000e+06,269061.0,...,304.0,8.0,4.0,338,11000,6.0,229012,596.0,153.0,8.7
156,Tora! Tora! Tora!,1970.0,Action|Drama|History|War,English,Japan,G,160.0,2.35,2.500000e+07,14500000.0,...,469.0,377.0,288.0,1548,0,0.0,25019,159.0,79.0,7.5
490,Akira,1988.0,Action|Animation|Sci-Fi,Japanese,Japan,R,124.0,1.85,1.100000e+09,439162.0,...,6.0,5.0,4.0,28,0,0.0,106160,430.0,150.0,8.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1375,Trainwreck,2015.0,Comedy|Romance,English,Japan,R,129.0,2.35,3.500000e+07,110008260.0,...,492.0,392.0,213.0,1450,25000,1.0,94241,309.0,332.0,6.3
1424,Godzilla Resurgence,2016.0,Action|Adventure|Drama|Horror|Sci-Fi,Japanese,Japan,NaN,120.0,2.35,NaN,NaN,...,544.0,106.0,12.0,699,0,0.0,374,13.0,1.0,8.2
1425,Godzilla Resurgence,2016.0,Action|Adventure|Drama|Horror|Sci-Fi,Japanese,Japan,NaN,120.0,2.35,NaN,NaN,...,544.0,106.0,12.0,699,0,0.0,374,13.0,1.0,8.2
1485,The Secret Life of Pets,2016.0,Animation|Comedy|Family,English,Japan,PG,87.0,1.85,7.500000e+07,323505540.0,...,1000.0,904.0,745.0,4782,36000,0.0,24407,155.0,165.0,6.8
1603,Yu-Gi-Oh! Duel Monsters,NaN,Action|Adventure|Animation|Family|Fantasy,Japanese,Japan,NaN,24.0,NaN,NaN,NaN,...,0.0,NaN,NaN,0,124,0.0,12417,51.0,6.0,7.0

In [69]:
movies.loc[(movies["Country"] == "Germany") & (movies["Language"] == "German")]

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
3,Metropolis,1927.0,Drama|Sci-Fi,German,Germany,Not Rated,145.0,1.33,6000000.0,26435.0,...,136.0,23.0,18.0,203,12000,1.0,111841,413.0,260.0,8.3
4,Pandora's Box,1929.0,Crime|Drama|Romance,German,Germany,Not Rated,110.0,1.33,NaN,9950.0,...,426.0,20.0,3.0,455,926,1.0,7431,84.0,71.0,8.0
1110,Run Lola Run,1998.0,Crime|Drama,German,Germany,R,81.0,1.85,3500000.0,7267324.0,...,486.0,37.0,34.0,623,0,1.0,161471,709.0,181.0,7.8
1176,Aimee & Jaguar,1999.0,Biography|Drama|Romance|War,German,Germany,NaN,125.0,1.85,15000000.0,927107.0,...,177.0,66.0,36.0,333,687,1.0,5153,51.0,63.0,7.3
9,Anatomy,2000.0,Horror|Thriller,German,Germany,R,103.0,2.35,8400000.0,5725.0,...,127.0,10.0,10.0,163,560,0.0,10220,110.0,62.0,6.1
614,Good Bye Lenin!,2003.0,Drama|Romance,German,Germany,R,121.0,1.85,4800000.0,4063859.0,...,65.0,51.0,43.0,200,11000,2.0,114407,225.0,153.0,7.7
792,Downfall,2004.0,Biography|Drama|History|War,German,Germany,R,178.0,1.85,13500000.0,5501940.0,...,918.0,653.0,471.0,2334,14000,0.0,248354,564.0,192.0,8.3
886,Summer Storm,2004.0,Comedy|Drama|Romance|Sport,German,Germany,R,98.0,1.85,2700000.0,95016.0,...,289.0,38.0,17.0,362,442,0.0,11074,56.0,40.0,7.4
1372,The Lives of Others,2006.0,Drama|Thriller,German,Germany,R,137.0,2.35,2000000.0,11284657.0,...,380.0,284.0,155.0,927,39000,3.0,259379,407.0,215.0,8.5
1764,The Baader Meinhof Complex,2008.0,Action|Biography|Crime|Drama,German,Germany,R,184.0,1.85,20000000.0,476270.0,...,486.0,471.0,155.0,1601,0,2.0,29602,110.0,160.0,7.4
1807,The Wave,2008.0,Drama|Thriller,German,Germany,NaN,107.0,2.35,5000000.0,NaN,...,287.0,150.0,93.0,635,25000,0.0,80639,96.0,93.0,7.6
2010,Soul Kitchen,2009.0,Comedy|Drama,German,Germany,NaN,99.0,1.85,4000000.0,274385.0,...,595.0,486.0,269.0,1519,0,3.0,29203,26.0,115.0,7.3
2076,The White Ribbon,2009.0,Drama|Mystery,German,Germany,R,144.0,1.85,12000000.0,2222647.0,...,63.0,43.0,16.0,167,0,0.0,52958,193.0,292.0,7.8
2,3,2010.0,Comedy|Drama|Romance,German,Germany,Unrated,119.0,2.35,NaN,59774.0,...,24.0,20.0,9.0,69,2000,0.0,4212,18.0,76.0,6.8
11,Animals United,2010.0,Animation|Comedy|Family,German,Germany,PG,93.0,2.39,NaN,NaN,...,1000.0,898.0,480.0,3095,885,0.0,4599,44.0,36.0,4.9

In [70]:
movies.loc[(movies["Country"] == "Germany") & (movies["Budget"] >= 6e+6)]

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
3,Metropolis,1927.0,Drama|Sci-Fi,German,Germany,Not Rated,145.0,1.33,6000000.0,26435.0,...,136.0,23.0,18.0,203,12000,1.0,111841,413.0,260.0,8.3
1058,City of Angels,1998.0,Drama|Fantasy|Romance,English,Germany,PG-13,114.0,2.35,55000000.0,78745923.0,...,12000.0,702.0,539.0,13905,0,1.0,94407,322.0,110.0,6.7
1059,Clay Pigeons,1998.0,Comedy|Crime,English,Germany,R,104.0,1.85,8000000.0,1789892.0,...,1000.0,261.0,168.0,1795,515,1.0,9494,109.0,49.0,6.6
1144,The Negotiator,1998.0,Action|Crime|Drama|Mystery|Thriller,English,Germany,R,140.0,2.35,50000000.0,44484065.0,...,18000.0,822.0,294.0,20152,3000,2.0,107227,279.0,68.0,7.3
1172,8MM,1999.0,Mystery|Thriller,English,Germany,R,123.0,2.35,40000000.0,36283504.0,...,12000.0,638.0,173.0,12970,0,1.0,104564,587.0,138.0,6.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231,30 Minutes or Less,2011.0,Action|Comedy|Crime,English,Germany,R,83.0,2.35,28000000.0,37053924.0,...,731.0,579.0,459.0,1987,0,3.0,77935,122.0,220.0,6.1
428,The Three Musketeers,2011.0,Action|Adventure|Romance,English,Germany,PG-13,110.0,2.35,75000000.0,20315324.0,...,14000.0,8000.0,5000.0,27694,19000,8.0,88542,254.0,228.0,5.8
489,Cloud Atlas,2012.0,Drama|Sci-Fi,English,Germany,R,172.0,2.35,102000000.0,27098580.0,...,15000.0,5000.0,1000.0,22686,124000,5.0,284825,828.0,511.0,7.5
573,Resident Evil: Retribution,2012.0,Action|Horror|Sci-Fi|Thriller,English,Germany,R,96.0,2.35,65000000.0,42345531.0,...,14000.0,1000.0,974.0,17913,32000,0.0,104831,423.0,239.0,5.4
759,Hansel & Gretel: Witch Hunters,2013.0,Action|Fantasy|Horror,English,Germany,R,98.0,2.35,50000000.0,55682070.0,...,10000.0,520.0,467.0,11946,45000,2.0,159868,304.0,349.0,6.1

In [71]:
movies

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
0,Intolerance: Love's Struggle Throughout the Ages,1916.0,Drama|History|War,NaN,USA,Not Rated,123.0,1.33,385907.0,NaN,...,436.0,22.0,9.0,481,691,1.0,10718,88.0,69.0,8.0
1,Over the Hill to the Poorhouse,1920.0,Crime|Drama,NaN,USA,NaN,110.0,1.33,100000.0,3000000.0,...,2.0,2.0,0.0,4,0,1.0,5,1.0,1.0,4.8
2,The Big Parade,1925.0,Drama|Romance|War,NaN,USA,Not Rated,151.0,1.33,245000.0,NaN,...,81.0,12.0,6.0,108,226,0.0,4849,45.0,48.0,8.3
3,Metropolis,1927.0,Drama|Sci-Fi,German,Germany,Not Rated,145.0,1.33,6000000.0,26435.0,...,136.0,23.0,18.0,203,12000,1.0,111841,413.0,260.0,8.3
4,Pandora's Box,1929.0,Crime|Drama|Romance,German,Germany,Not Rated,110.0,1.33,NaN,9950.0,...,426.0,20.0,3.0,455,926,1.0,7431,84.0,71.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1599,War & Peace,NaN,Drama|History|Romance|War,English,UK,TV-14,NaN,16.00,NaN,NaN,...,1000.0,888.0,502.0,4528,11000,1.0,9277,44.0,10.0,8.2
1600,Wings,NaN,Comedy|Drama,English,USA,NaN,30.0,1.33,NaN,NaN,...,685.0,511.0,424.0,1884,1000,5.0,7646,56.0,19.0,7.3
1601,Wolf Creek,NaN,Drama|Horror|Thriller,English,Australia,NaN,NaN,2.00,NaN,NaN,...,511.0,457.0,206.0,1617,954,0.0,726,6.0,2.0,7.1
1602,Wuthering Heights,NaN,Drama|Romance,English,UK,NaN,142.0,NaN,NaN,NaN,...,27000.0,698.0,427.0,29196,0,2.0,6053,33.0,9.0,7.7
1603,Yu-Gi-Oh! Duel Monsters,NaN,Action|Adventure|Animation|Family|Fantasy,Japanese,Japan,NaN,24.0,NaN,NaN,NaN,...,0.0,NaN,NaN,0,124,0.0,12417,51.0,6.0,7.0

In [74]:
movies.loc[~movies["Year"].isna()]

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
0,Intolerance: Love's Struggle Throughout the Ages,1916.0,Drama|History|War,NaN,USA,Not Rated,123.0,1.33,385907.0,NaN,...,436.0,22.0,9.0,481,691,1.0,10718,88.0,69.0,8.0
1,Over the Hill to the Poorhouse,1920.0,Crime|Drama,NaN,USA,NaN,110.0,1.33,100000.0,3000000.0,...,2.0,2.0,0.0,4,0,1.0,5,1.0,1.0,4.8
2,The Big Parade,1925.0,Drama|Romance|War,NaN,USA,Not Rated,151.0,1.33,245000.0,NaN,...,81.0,12.0,6.0,108,226,0.0,4849,45.0,48.0,8.3
3,Metropolis,1927.0,Drama|Sci-Fi,German,Germany,Not Rated,145.0,1.33,6000000.0,26435.0,...,136.0,23.0,18.0,203,12000,1.0,111841,413.0,260.0,8.3
4,Pandora's Box,1929.0,Crime|Drama|Romance,German,Germany,Not Rated,110.0,1.33,NaN,9950.0,...,426.0,20.0,3.0,455,926,1.0,7431,84.0,71.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1492,Warcraft,2016.0,Action|Adventure|Fantasy,English,USA,PG-13,123.0,2.35,160000000.0,46978995.0,...,3000.0,716.0,648.0,5505,89000,0.0,111609,781.0,275.0,7.3
1493,Xi you ji zhi: Sun Wukong san da Baigu Jing,2016.0,Action|Adventure|Fantasy,English,China,NaN,119.0,2.35,68005000.0,NaN,...,879.0,107.0,22.0,1026,426,1.0,1212,9.0,14.0,6.0
1494,X-Men: Apocalypse,2016.0,Action|Adventure|Sci-Fi,English,USA,PG-13,144.0,2.35,178000000.0,154985087.0,...,34000.0,13000.0,1000.0,49684,54000,6.0,148379,622.0,396.0,7.3
1495,Yoga Hosers,2016.0,Comedy|Fantasy|Horror|Thriller,English,USA,PG-13,88.0,NaN,5000000.0,NaN,...,40000.0,3000.0,1000.0,46115,0,7.0,849,4.0,35.0,4.8
1496,Zoolander 2,2016.0,Comedy,English,USA,PG-13,102.0,2.35,50000000.0,28837115.0,...,14000.0,8000.0,1000.0,24107,28000,4.0,34964,150.0,226.0,4.8

In [75]:
movies.loc[movies["Genres"] == "Sci-Fi"]

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
217,Damnation Alley,1977.0,Sci-Fi,English,USA,PG,91.0,2.35,17000000.0,NaN,...,669.0,642.0,255.0,1769,903,0.0,3701,71.0,41.0,5.2
1024,The Sticky Fingers of Time,1997.0,Sci-Fi,English,USA,NaN,81.0,1.85,250000.0,18195.0,...,119.0,24.0,5.0,154,67,0.0,336,7.0,8.0,6.3
1045,Mutant World,2014.0,Sci-Fi,English,Canada,NaN,82.0,NaN,1500000.0,NaN,...,341.0,265.0,146.0,967,236,0.0,459,10.0,4.0,2.8

In [76]:
movies.loc[movies["Genres"].str.contains("Sci-Fi")]

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
3,Metropolis,1927.0,Drama|Sci-Fi,German,Germany,Not Rated,145.0,1.33,6000000.0,26435.0,...,136.0,23.0,18.0,203,12000,1.0,111841,413.0,260.0,8.3
56,"The Beast from 20,000 Fathoms",1953.0,Adventure|Horror|Sci-Fi,English,USA,Approved,80.0,1.37,210000.0,5000000.0,...,57.0,40.0,21.0,205,465,0.0,4812,88.0,67.0,6.7
58,"20,000 Leagues Under the Sea",1954.0,Adventure|Drama|Family|Fantasy|Sci-Fi,English,USA,Approved,127.0,1.37,5000000.0,NaN,...,617.0,53.0,51.0,799,0,0.0,22123,108.0,69.0,7.2
59,"20,000 Leagues Under the Sea",1954.0,Adventure|Drama|Family|Fantasy|Sci-Fi,English,USA,Approved,127.0,1.37,5000000.0,NaN,...,618.0,53.0,51.0,800,0,0.0,22124,108.0,69.0,7.2
86,The Brain That Wouldn't Die,1962.0,Horror|Sci-Fi,English,USA,Approved,70.0,1.66,62000.0,NaN,...,24.0,16.0,6.0,52,1000,1.0,4752,152.0,95.0,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1567,Space: Above and Beyond,NaN,Drama|Sci-Fi,English,USA,NaN,60.0,1.33,5000000.0,NaN,...,210.0,121.0,109.0,611,963,0.0,6381,79.0,8.0,7.7
1569,Star Wars: The Clone Wars,NaN,Action|Adventure|Animation|Drama|Fantasy|Sci-Fi,English,USA,TV-PG,23.0,2.35,NaN,NaN,...,668.0,296.0,265.0,1484,2000,0.0,28190,73.0,47.0,7.9
1570,Stargate SG-1,NaN,Action|Adventure|Drama|Sci-Fi,English,USA,TV-14,44.0,1.33,1400000.0,NaN,...,847.0,440.0,72.0,1359,0,4.0,63982,181.0,77.0,8.4
1577,The Dead Zone,NaN,Drama|Fantasy|Mystery|Sci-Fi,English,Canada,TV-14,60.0,NaN,NaN,NaN,...,443.0,319.0,186.0,981,576,1.0,7122,77.0,18.0,7.5
1589,The Powerpuff Girls,NaN,Action|Animation|Comedy|Family|Fantasy|Sci-Fi,English,USA,TV-Y7,30.0,4.00,NaN,NaN,...,971.0,918.0,265.0,2346,581,0.0,23664,60.0,7.0,7.2

In [79]:
movies.loc[movies["Genres"].str.contains("sci-fi", case=False)]

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
3,Metropolis,1927.0,Drama|Sci-Fi,German,Germany,Not Rated,145.0,1.33,6000000.0,26435.0,...,136.0,23.0,18.0,203,12000,1.0,111841,413.0,260.0,8.3
56,"The Beast from 20,000 Fathoms",1953.0,Adventure|Horror|Sci-Fi,English,USA,Approved,80.0,1.37,210000.0,5000000.0,...,57.0,40.0,21.0,205,465,0.0,4812,88.0,67.0,6.7
58,"20,000 Leagues Under the Sea",1954.0,Adventure|Drama|Family|Fantasy|Sci-Fi,English,USA,Approved,127.0,1.37,5000000.0,NaN,...,617.0,53.0,51.0,799,0,0.0,22123,108.0,69.0,7.2
59,"20,000 Leagues Under the Sea",1954.0,Adventure|Drama|Family|Fantasy|Sci-Fi,English,USA,Approved,127.0,1.37,5000000.0,NaN,...,618.0,53.0,51.0,800,0,0.0,22124,108.0,69.0,7.2
86,The Brain That Wouldn't Die,1962.0,Horror|Sci-Fi,English,USA,Approved,70.0,1.66,62000.0,NaN,...,24.0,16.0,6.0,52,1000,1.0,4752,152.0,95.0,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1567,Space: Above and Beyond,NaN,Drama|Sci-Fi,English,USA,NaN,60.0,1.33,5000000.0,NaN,...,210.0,121.0,109.0,611,963,0.0,6381,79.0,8.0,7.7
1569,Star Wars: The Clone Wars,NaN,Action|Adventure|Animation|Drama|Fantasy|Sci-Fi,English,USA,TV-PG,23.0,2.35,NaN,NaN,...,668.0,296.0,265.0,1484,2000,0.0,28190,73.0,47.0,7.9
1570,Stargate SG-1,NaN,Action|Adventure|Drama|Sci-Fi,English,USA,TV-14,44.0,1.33,1400000.0,NaN,...,847.0,440.0,72.0,1359,0,4.0,63982,181.0,77.0,8.4
1577,The Dead Zone,NaN,Drama|Fantasy|Mystery|Sci-Fi,English,Canada,TV-14,60.0,NaN,NaN,NaN,...,443.0,319.0,186.0,981,576,1.0,7122,77.0,18.0,7.5
1589,The Powerpuff Girls,NaN,Action|Animation|Comedy|Family|Fantasy|Sci-Fi,English,USA,TV-Y7,30.0,4.00,NaN,NaN,...,971.0,918.0,265.0,2346,581,0.0,23664,60.0,7.0,7.2